In [1]:
import numpy as np

In [2]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [4]:
x2 = np.array([1, 2, 3, 4])
print(x2)

[1 2 3 4]


In [5]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [6]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [17]:
z2 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[4, 5, 6], [4, 5, 6], [4, 5, 6]]])
z3 = np.array([[[1, 1, 1], [1, 1, 1], [1, 1, 1]], [[2, 2, 2], [2, 2, 2], [2, 2, 2]]])

print(z3)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


In [18]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
b2 = np.arange(12).reshape(3, 4)

print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
print('type:', type(b2), '.shape:', b2.shape, 'size:', b2.size, 'ndim:', b2.ndim)

type: <class 'numpy.ndarray'> .shape: (3, 4) size: 12 ndim: 2


In [ ]:
type(b)

In [32]:
b.shape

(2, 5)

In [33]:
b.size

10

In [34]:
b.ndim

2

Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [49]:
ex1 = np.arange(1, 19).reshape(3, 3, 2)
print(ex1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [ ]:
print('type:', type(ex1), '.shape:', ex1.shape, 'size:', ex1.size, 'ndim:', ex1.ndim)

In [50]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Exercise2:Extract the value 15 from the z array above by indexing

In [56]:
z2 = z[1, 1, 2]
print(z2)

15


In [ ]:
##array slice

In [57]:
z[1, 2, :]

array([16, 17, 18])

In [60]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [58]:
y[:2, :]

array([[4, 5, 0],
       [3, 7, 9]])

In [61]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [62]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [64]:
ex3 = z[1,0:2 ,:]
print(ex3)

[[10 11 12]
 [13 14 15]]


In [65]:
##vectorizing and summarizing

In [67]:
x = np.array([5, 4, -7, 11])
print(x)

[ 5  4 -7 11]


In [66]:
x+2

array([ 7,  6, -5, 13])

In [68]:
x-1

array([ 4,  3, -8, 10])

In [69]:
x**2

array([ 25,  16,  49, 121])

In [70]:
np.abs(x)

array([ 5,  4,  7, 11])

In [71]:
np.max(x)

11

In [72]:
np.median(x)

4.5

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

In [89]:
ex4_ary = [1, 2, 3, 4, 5, 6]
ex4_len = len(ex4_ary)


if ex4_len % 2 == 0:
    median = (ex4_ary[int(ex4_len/2)] + ex4_ary[int(ex4_len/2 -1)])/2
else:
    median = ex4_ary[int(ex4_len/2)]

print(median)
        

3.5


Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [93]:
ex5_ary = [1, 2, 3, 4, 5, 6]

np.median(ex5_ary)


3.5

In [94]:
x<5 

array([False,  True,  True, False])

In [95]:
x==11

array([False, False, False,  True])

In [98]:
~(x > 1)

array([False, False,  True, False])

In [ ]:
##masks for subsetting

In [106]:
x[x < 5]

array([ 4, -7])

In [107]:
x[x < 5]=40
x


array([ 5, 40, 40, 11])

Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [140]:
x = np.array([5, 4, -7, 11, 12])

In [135]:
x[~(x > 20)|(x == 11)] = 30
x

array([30, 30, 30, 30, 30])

In [136]:
np.sum(x)

150

In [139]:
np.sum(x<35)

5

In [150]:
y

array([[4, 5, 0],
       [3, 7, 9],
       [2, 1, 2]])

In [145]:
np.sum(y, axis=0)

array([ 9, 13, 11])

In [151]:
np.sum(y, axis=1)

array([ 9, 19,  5])

In [147]:
##row-column
np.sum(z, axis=0)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [148]:
##column-layer
np.sum(z, axis=1)

array([[12, 15, 18],
       [39, 42, 45]])

In [149]:
##row-layer
np.sum(z, axis=2)

array([[ 6, 15, 24],
       [33, 42, 51]])

Exercise7: Calculate the mean of all column in each layer from array z.

In [ ]:
## ploting an array

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
h = y.flatten()
h

In [ ]:
plt.hist(h);

In [ ]:
plt.plot(y[1, :]);

In [ ]:
plt.plot(y[:, 1]);

In [ ]:
plt.plot(y);

In [ ]:
plt.imshow(y);

In [ ]:
##practice with plotting on different arrays

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

plt.hist(data, bins=[0,2,4,6,8,10])
plt.title('My Histogram')
plt.xlabel('Interval')
plt.ylabel('Frequency')
plt.show()


Exercise8: Given an 2D array of numbers, plot a graph that displays the sum of each element in the column.


Reference: https://docs.python.org
https://geobgu.xyz/py/numpy.html 